#!/bin/bash

if ! pacman -Qi archiso > /dev/null; then
    echo "archiso is not installed. Installing archiso..."
    sudo pacman -Sy archiso --needed --noconfirm
fi

if [ -d "work" ] || [ -d "out" ]; then
  sudo rm -rf work/ out/
fi

if grep -wq "plasma" profiledef.sh && ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    echo "Adding Chaotic AUR to pacman.conf"
	sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB
    sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' 
    sudo sh -c "echo -e '\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' >> /etc/pacman.conf"
    sudo pacman -Syu
fi

echo "Building ISO"
echo "Warning don't press ctrl+c or ctrl+z when iso is building"
sudo mkarchiso -vvv -w ./work -o ./out ./