// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1622821224);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1622821254);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1622821194);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"95140\":1622821210498,\"95188\":1622821210501,\"95260\":1622821210502}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{be3060c6-0d0d-4f0a-a9e9-5922412ad2d7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1622821197);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1622821223159");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1622823041159");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1622821201580");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1622842801580");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1622821197");
user_pref("browser.startup.homepage_override.buildID", "20210531160138");
user_pref("browser.startup.homepage_override.mstone", "89.0");
user_pref("browser.startup.lastColdStartupCheck", 1622821196);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"plasma-browser-integration_kde_org-browser-action\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"plasma-browser-integration_kde_org-browser-action\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1622821198900");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "89.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "befd1cb4d7bc49ec93a346cc43f64fd6");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210531160138");
user_pref("extensions.lastAppVersion", "89.0");
user_pref("extensions.lastPlatformVersion", "89.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.plasma-browser-integration@kde.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3eaa0e9f-b8c4-4f50-9b44-7fd9216c3ea4\",\"formautofill@mozilla.org\":\"75816218-51e2-4f9a-be51-29f0ca198f98\",\"pictureinpicture@mozilla.org\":\"a5931c65-6e41-4010-b308-a054fa02670f\",\"screenshots@mozilla.org\":\"921bee16-b841-49ac-8c8c-23b66eccc6ac\",\"webcompat-reporter@mozilla.org\":\"4a0e2018-c818-4734-af83-d0cce9caaa1b\",\"webcompat@mozilla.org\":\"e452010e-afba-4df0-9ca8-10d035e49fbb\",\"default-theme@mozilla.org\":\"8b9144ff-1e45-4cbb-b0d9-e8df843c65ca\",\"google@search.mozilla.org\":\"b795a742-ef27-40d5-b54a-278c2b778c1b\",\"amazondotcom@search.mozilla.org\":\"9c309544-53bf-4e8e-8f61-a397896e76d8\",\"wikipedia@search.mozilla.org\":\"57c8e1b3-9e02-4c7b-a66a-53799ca14d0c\",\"bing@search.mozilla.org\":\"1715bd84-cb39-4411-8fe7-2e74863dfd3c\",\"ddg@search.mozilla.org\":\"48023a7e-a9d1-40b8-a21a-2a9a5317d1f1\",\"firefox-compact-dark@mozilla.org\":\"9d762063-d9fa-4a97-b926-8136b60b7005\",\"addon@darkreader.org\":\"c30e0a1e-99f4-40a1-96e2-574713a3ce40\",\"plasma-browser-integration@kde.org\":\"2595a0ae-500d-40f0-890c-1c2d8ee127eb\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1622821198);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "05e276b9-57a3-4e46-9880-2188d3dcc260");
user_pref("toolkit.startup.last_success", 1622821193);
user_pref("toolkit.telemetry.cachedClientID", "47313b90-687d-477c-9aed-7fa09fa9e5df");
user_pref("toolkit.telemetry.previousBuildID", "20210531160138");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
