// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "90a2c3f2-0e5f-4e5c-8d43-c25eefa889da");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1613466341);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1613466332);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1613466325);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1613466370);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1613466310);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f2911ed0-b23b-48d7-a24f-39c78d16f869}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1613466324);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1613466369794");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1613468190794");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1613466331316");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1613487931316");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1613466323");
user_pref("browser.slowStartup.averageTime", 17700);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210210003430");
user_pref("browser.startup.homepage_override.mstone", "85.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1613466319);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1613466328695");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "85.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "85c9ac1c9e9f4a6d81cb8905a1200636");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210210003430");
user_pref("extensions.lastAppVersion", "85.0.2");
user_pref("extensions.lastPlatformVersion", "85.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.recommendations.hideNotice", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e0c738ab-bf9c-4125-b05f-852cab2aef45\",\"formautofill@mozilla.org\":\"87024dbd-458f-4647-9886-8ddb333aae5f\",\"screenshots@mozilla.org\":\"0ecfeee5-aaf1-4628-a107-45cec12f18bf\",\"webcompat-reporter@mozilla.org\":\"6a415e80-acec-4202-8193-72a5b77c1b88\",\"webcompat@mozilla.org\":\"df81245f-c946-4050-9087-ca22e78b9711\",\"default-theme@mozilla.org\":\"6cd5744f-14b3-44be-b53d-7bacfe47eb4f\",\"google@search.mozilla.org\":\"97f83d8d-2e98-4929-b5ca-e4ffc05bdded\",\"amazondotcom@search.mozilla.org\":\"2ec3379f-609e-4637-9787-1b4367da68da\",\"wikipedia@search.mozilla.org\":\"9a9531f8-9d47-4545-bc69-4694958bd27d\",\"bing@search.mozilla.org\":\"1d8552ef-5001-40f3-8e05-e727905504af\",\"ddg@search.mozilla.org\":\"2f8f1aff-05e2-4839-883a-e2833c80bf35\",\"firefox-compact-dark@mozilla.org\":\"e6ca4f30-1ce3-449c-9038-a05489608d12\",\"addon@darkreader.org\":\"23ef64bb-8de7-40ff-9f5a-e37dd1a3cbcd\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ff3e7082-5bdd-4c57-87d2-904e86a87e3e");
user_pref("security.sandbox.plugin.tempDirSuffix", "ae214af0-8b9e-4ec3-a456-b46c443e9f98");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1613466303);
user_pref("toolkit.telemetry.cachedClientID", "a32643bd-0646-487b-b95c-ec46562f1d96");
user_pref("toolkit.telemetry.previousBuildID", "20210210003430");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
