// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "7678b852-5fa5-4000-ab14-a1ae355d07a4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1613197293);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1613197283);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1613204757);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1613198002);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1613197323);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1613197262);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"84385\":1613197281827,\"84413\":1613197281820,\"84447\":1613197281826}");
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{aa89c9b8-8e7b-48d9-84c3-5e16868f7fba}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1613197273);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1613204760280");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1613206573280");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1613197286670");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1613218886670");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210210003430");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1613204757");
user_pref("browser.slowStartup.averageTime", 8103);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20210210003430");
user_pref("browser.startup.homepage_override.mstone", "85.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1613204756);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\",\"plasma-browser-integration_kde_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\",\"plasma-browser-integration_kde_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1613197982937");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "85.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "295ac95caf6048c3b6526b0f4d5d4d75");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210210003430");
user_pref("extensions.lastAppVersion", "85.0.2");
user_pref("extensions.lastPlatformVersion", "85.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.plasma-browser-integration@kde.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"73c8ee18-3c49-4a42-8dbc-0ac8ddcf8df1\",\"formautofill@mozilla.org\":\"60b293d4-c0f3-4fb8-ba9a-fd206ff24c77\",\"screenshots@mozilla.org\":\"4ef0c8c8-a81e-47c1-a090-e9b06b3066ba\",\"webcompat-reporter@mozilla.org\":\"5194c21d-1eb0-493b-8cd5-c18fecad3fab\",\"webcompat@mozilla.org\":\"d5bb3dc8-ec76-4809-9b0b-3a76578190e9\",\"default-theme@mozilla.org\":\"e59647f4-10e8-4b5d-bca4-f09ba64855e1\",\"google@search.mozilla.org\":\"1dfd37da-ce54-4b4e-9774-cb7f4d9ed623\",\"amazondotcom@search.mozilla.org\":\"b178bf0b-d9de-4fcc-b9fe-8e9273dd7a77\",\"wikipedia@search.mozilla.org\":\"22864433-eb64-402d-abeb-7dd038877000\",\"bing@search.mozilla.org\":\"1095a0b8-ba29-4920-a581-97b3dfa32720\",\"ddg@search.mozilla.org\":\"e6cef8dd-b0fc-4adb-b143-e0f4f8df18db\",\"firefox-compact-dark@mozilla.org\":\"3bda1a3f-a36a-4ca1-9b2e-fef735dca7cf\",\"addon@darkreader.org\":\"9186a279-5525-4093-a297-d3db21e419d6\",\"plasma-browser-integration@kde.org\":\"3d282e95-763c-4168-aef5-a7e79c12a52c\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "5d9d9ea2-577d-488a-a6ab-f6f868b7cde1");
user_pref("security.sandbox.plugin.tempDirSuffix", "0a74666e-ac2c-4c02-b470-16128d7b6e4a");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1613204748);
user_pref("toolkit.telemetry.cachedClientID", "16c43e44-fe5c-4f46-8dc0-6a190c8934ba");
user_pref("toolkit.telemetry.previousBuildID", "20210210003430");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
